rom = "/Users/frank/Development/projects/kickroms/kick31.rom"

[machine]
profile = "A500"

[cpu]
model = "68000"

[chipset]
revision = "ECS"

[memory]
chip = "2M"

[floppy]
drives = 2

[floppy.df1]
path = "/Users/frank/Development/projects/amiga/hydron/dist/Hydron.adf"

[input]
joystick = "keyboard"

[[filesys]]
path = "/Users/frank/Development/projects/amiga/hydron/uae/dh0"
volume = "dh0"
bootpri = -128
